version: '3.8'

services:
    nginx:
        build:
            context: backend
            dockerfile: ./nginx/Dockerfile
        volumes:
            - static_volume:/home/app/web/app/static/
        ports:
            - "1337:80"
        depends_on:
            - web

    web:
        build:
            context: backend
            dockerfile: ./docker/Dockerfile.dev
        # It exposes 4 processes on the container address 0.0.0.0 loading
        # the object app from the wsgi.py file
        command: ["gunicorn", "--workers", "4", "--bind", "0.0.0.0", "wsgi:app"]
        volumes:
            - static_volume:/home/app/web/app/static/
        ports:
            # By default Gunicorn exposes port 8000
            - 8000
        env_file:
            - ./config/.prod.env
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data_prod:/var/lib/postgresql/data/
        env_file:
            - ./config/.prod.env

volumes:
    postgres_data_prod:
    static_volume:
