version: '3.8'

services:
    db:
        image: postgres:13-alpine
        command: ["postgres", "-c", "log_statement=all"]
        ports:
            - "5433:5432"
        env_file:
            - ./config/.test.env
