version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
        # 127.0.0.1 is a default value.
        # Here we need to bind our service to the 0.0.0.0
        # to make it accessible to machines other than docker.
        # Otherwise the service will be only accessible
        # from the docker localhost
        command: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
        volumes:
            - .:/usr/src/app/
        ports:
            - "5000:5000"
        env_file:
            - ./config/.dev.env

    db:
        image: postgres:13-alpine
        command: ["postgres", "-c", "log_statement=all"]
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./config/.dev.env

volumes:
    postgres_data:
