version: '3.8'

services:
    backend:
        build:
            # Dockerfile needs an access to the files in the parent folder
            # that's why the context should be ./backed rather than ./backend/docker
            context: ./backend
            dockerfile: ./docker/Dockerfile.dev
        # 127.0.0.1 is a default value.
        # Here we need to bind our service to the 0.0.0.0
        # to make it accessible to machines other than docker.
        # Otherwise the service will be only accessible
        # from the docker localhost
        command: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
        volumes:
            - ./backend:/usr/src/app:rw
        ports:
            - "5000:5000"
        env_file:
            - ./backend/config/.dev.env
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        command: ["postgres", "-c", "log_statement=all"]
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./backend/config/.dev.env

    frontend:
        build:
            context: ./frontend
            dockerfile: ./docker/Dockerfile.dev
        command: ["npm", "start"]
        volumes:
            - ./frontend:/app:rw
        ports:
            - "3000:3000"
        depends_on:
            - backend



volumes:
    postgres_data:
