import os
import psycopg2

def get_db_connection():
    return psycopg2.connect(
                host=os.environ["DB_HOST"],
                database=os.environ["DB_NAME"],
                user=os.environ["DB_USERNAME"],
                password=os.environ["DB_PASSWORD"])

def init_db():
    # Open a cursor to perform database operations
    # Cursor allows python to execute PostgreSQL command in
    # a database section
    with get_db_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS currency CASCADE;")
            cursor.execute("DROP TABLE IF EXISTS portfolio;")

            # Create a currency table
            # [SERIAL]
            # Creates a sequence object that generate a sequence of integers
            # Sets the next value generated by the sequence as the default value from the object
            # Adds a NOT NULL constraint to the column
            # Assignes the owner of the sequence to the column
            # [NOT NULL]
            # Prevents from inserting NULL values into the database
            cursor.execute('CREATE TABLE currency (currency_id SERIAL PRIMARY KEY,'
                                                'currency_code CHAR (3) NOT NULL,'
                                                'currency_name VARCHAR (50) NOT NULL);')

            # Create a portfolio table
            cursor.execute('CREATE TABLE portfolio (portfolio_id SERIAL PRIMARY KEY,'
                                                'portfolio_name varchar (150) NOT NULL,'
                                                'user_id INTEGER NOT NULL,'
                                                'currency_id INTEGER NOT NULL,'
                                                'creation_date DATE DEFAULT CURRENT_DATE,'
                                                'CONSTRAINT fk_currency '
                                                        'FOREIGN KEY(currency_id) '
                                                            'REFERENCES currency(currency_id) '
                                                            'ON DELETE CASCADE);')

            # Insert data into the currency table
            currencies = [
                ("USD", "United States dollar"),
                ("EUR", "Euro")
            ]
            cursor.executemany('INSERT INTO currency (currency_code, currency_name)'
                                    'VALUES(%s, %s)',
                               currencies)

            # Insert data into the portfolio table
            portfolios = [
                ("Tech companies", 1, 1),
                ("High yield bonds", 2, 2)
            ]
            cursor.executemany('INSERT INTO portfolio (portfolio_name, user_id, currency_id)'
                                    'VALUES(%s, %s, %s)',
                               portfolios)

            connection.commit()

if __name__ == '__main__':
    init_db()